Repository containers/common, pull requests merged in 2020-12, with the labels that each got.

#369 Remove libpod.conf
  pkg/config/config.go
  pkg/config/libpodConfig.go
Labels: 3.0 Release, approved, lgtm

#371 Add a volume plugins field to containers.conf
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/containers.conf
Labels: 3.0 Release, approved, lgtm

#370 Switch default runtime from runc to crun
  pkg/config/containers.conf
  pkg/config/default.go
Labels: 3.0 Release, approved, lgtm

#373 Bump to v0.31.0
  version/version.go
Labels: approved

#381 Add pidfd_open syscall by default
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved

#382 Find ociruntime instead of hard coding default
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/containers.conf
  pkg/config/default.go
Labels: approved, lgtm

#384 Bump to v0.31.1
  version/version.go
Labels: approved

#386 Switch references of /var/run -> /run
  docs/containers.conf.5.md
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_comment.conf
  pkg/config/testdata/containers_default.conf
  pkg/config/testdata/containers_invalid.conf
Labels: approved, lgtm

#387 Fix building on non linux platforms
  pkg/seccomp/seccomp_unsupported.go
  pkg/seccomp/supported.go
  pkg/seccomp/supported_test.go
Labels: approved, lgtm

#389 Bump to v0.31.2
  version/version.go
Labels: approved

#388 Add support for DOCKER_CONFIG
  pkg/auth/auth.go
  pkg/auth/auth_test.go
Labels: approved, lgtm

#391 Add completions for --arch and --os
  pkg/completion/completion.go
Labels: approved, lgtm
