Repository containers/common, pull requests merged in 2020-10, with the labels that each got.

#318 Bump to v0.24.0
  version/version.go
Labels: approved

#319 Specify the recommended defaults for security
  pkg/config/containers.conf
Labels: approved, lgtm

#322 Bump to v0.25.0
  version/version.go
Labels: approved

#323 Fix description of no-common options for cgroups
  docs/containers.conf.5.md
  pkg/config/containers.conf
Labels: approved, lgtm

#324 Consolidate reporting functions
  pkg/report/camelcase/LICENSE.md
  pkg/report/camelcase/README.md
  pkg/report/camelcase/camelcase.go
  pkg/report/doc.go
  pkg/report/template.go
  pkg/report/template_test.go
  pkg/report/validate.go
  pkg/report/validate_test.go
  pkg/report/writer.go
  pkg/report/writer_test.go
Labels: approved, do-not-merge/work-in-progress

#327 Bump to v0.26.0
  version/version.go
Labels: approved

#331 Add time64 syscalls to seccomp.json
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved, lgtm

#332 Fix --format corner cases
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#333 Bump to v0.26.1
  version/version.go
Labels: approved

#335 Set storage path correctly
  pkg/config/default.go
Labels: approved, lgtm

#336 Bump to v0.26.2
  version/version.go
Labels: approved

#339 Don't check for timezone, unless user specified one
  pkg/config/config_local.go
Labels: approved, lgtm

#340 Revert changes in 0.26.2 that broke podman
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#341 Bump to v0.26.3
  version/version.go
Labels: approved

#342 Enabled the remote flag to be accessible by users
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/containers.conf
Labels: approved, lgtm
