Repository containers/common, pull requests merged in 2021-02, with the labels that each got.

#426 Add compatible template functions
  pkg/report/doc.go
  pkg/report/template.go
  pkg/report/template_test.go
Labels: 3.0 Release, approved, lgtm

#427 Change default log driver to journald
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_override.conf
Labels: 3.0 Release, approved, lgtm

#424 Add image_default_format
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/testdata/containers_override.conf
Labels: approved, lgtm

#428 Bump to v0.34.0
  version/version.go
Labels: approved

#430 Bump to v0.33.2
  version/version.go
Labels: approved

#433 Revert change to journald as default
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_override.conf
  version/version.go
Labels: approved, lgtm

#435 [v0.29] Backport: Add compatible template functions
  pkg/report/doc.go
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#438 Updated report.template to be more compatible
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#439 Bump to v0.33.4
  pkg/report/template.go
  pkg/report/template_test.go
  version/version.go
Labels: approved, lgtm

#440 Bump to v0.34.1
  version/version.go
Labels: approved

#441 Revert "Change default log driver to journald"
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_override.conf
Labels: approved

#444 Revert "Bump github.com/opencontainers/runc from 1.0.0-rc91 to 1.0.0-…
  go.mod
  go.sum
  pkg/chown/chown.go
  pkg/chown/chown_test.go
  pkg/chown/chown_windows.go
  pkg/parse/parse_unix.go
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/LICENSE
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/vendor.conf
  vendor/github.com/cyphar/filepath-securejoin/vfs.go
  vendor/github.com/golang/protobuf/proto/text_decode.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_disabled.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/fscommon.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/open.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/v1_utils.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/modules.txt
Labels: approved, lgtm

#445 update pause image to 3.4.1
  docs/containers.conf.5.md
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_comment.conf
  pkg/config/testdata/containers_default.conf
  pkg/config/testdata/containers_invalid.conf
Labels: approved, lgtm

#447 Add missing values to containers.conf man page
  docs/containers.conf.5.md
  pkg/config/containers.conf
Labels: approved, lgtm

#454 Move EnforceRange and HasTable out of Podman and into common
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#456 Bump to v0.35.0
  version/version.go
Labels: approved

#459 Completion
  pkg/completion/completion.go
Labels: approved

#463 Stop logging messages about using DOCKER_CONFIG
  pkg/auth/auth.go
Labels: approved, lgtm

#464 Bump to v0.35.1
  version/version.go
Labels: approved

#465 Cherry-pick: v0.33 Stop logging messages about using DOCKER_CONFIG
  pkg/auth/auth.go
  version/version.go
Labels: approved, lgtm
