Repository containers/common, pull requests merged in 2021-07, with the labels that each got.

#656 Report bad entries in containers.conf to the user
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testdata/containers_broken.conf
Labels: approved, lgtm

#658 0.38 backports
  libimage/image.go
  libimage/load.go
  libimage/manifest_list.go
  libimage/pull.go
  libimage/push.go
  libimage/save.go
  version/version.go
Labels: approved, lgtm

#660 libimage: force internal image lookups to ignore arch
  libimage/filters.go
  libimage/pull.go
  libimage/save.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: approved, lgtm

#663 0.38 backports
  libimage/filters.go
  libimage/pull.go
  libimage/save.go
  version/version.go
Labels: approved, lgtm

#667 Fix default definition of secrets in containers.conf
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/containers.conf
Labels: approved, lgtm

#668 [0.38] Don't use systemd defaults if /proc/1/comm != systemd
  Makefile
  pkg/config/config_test.go
  pkg/config/default.go
  pkg/config/nosystemd.go
  pkg/config/systemd.go
Labels: approved, lgtm

#669 libimage: import: fix tags
  libimage/import.go
  libimage/import_test.go
Labels: approved, lgtm, needs-backport

#664 libimage: LookupImage: remove IgnorePlatform option
  libimage/filters.go
  libimage/manifest_list.go
  libimage/pull.go
  libimage/pull_test.go
  libimage/push.go
  libimage/runtime.go
  libimage/save.go
Labels: approved, lgtm

#670 [0.38] libimage: import: fix tags
  libimage/import.go
  libimage/import_test.go
Labels: approved, lgtm

#671 v0.38.15
  version/version.go
Labels: approved

#674 Bump to v0.41.0
  version/version.go
Labels: approved

#673 libimage: image tree: fix nil deref
  libimage/image_tree.go
Labels: approved, lgtm

#677 add config option for ChownCopiedFiles
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/default.go
Labels: approved, lgtm

#678 User option to prepare container after creation for volume copy-up.
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/containers.conf
Labels: approved, lgtm

#679 pull with custom platform: handle "localhost/"
  libimage/pull.go
Labels: approved, lgtm

#680 0.38 backports
  libimage/pull.go
  version/version.go
Labels: approved, lgtm

#683 libimage.RuntimeFromStore(): stop overriding the BlobInfoCache location
  libimage/runtime.go
Labels: approved, lgtm

#684 fix "dangling" filter and pruning
  libimage/filters.go
  libimage/image.go
  libimage/image_test.go
  libimage/layer_tree.go
  libimage/runtime.go
Labels: approved, lgtm

#685 libimage: pull: normalize docker-daemon
  libimage/pull.go
  libimage/pull_test.go
Labels: approved, lgtm

#689 [0.38] seccomp: add support for defaultErrnoRet
  pkg/seccomp/conversion.go
  pkg/seccomp/filter.go
  pkg/seccomp/seccomp_linux.go
  pkg/seccomp/types.go
  version/version.go
Labels: approved, lgtm

#690 pkg/seccomp: avoid DefaultErrnoRet: null
  pkg/seccomp/types.go
Labels: approved, lgtm

#691 Bump to v0.38.18
  version/version.go
Labels: approved

#688 Add and use libimage.Runtime.imageIDsForManifest()
  libimage/copier.go
  libimage/image.go
  libimage/import.go
  libimage/pull.go
Labels: approved, lgtm

#695 config: split arguments in DBUS_SESSION_BUS_ADDRESS
  pkg/config/config.go
Labels: approved, lgtm

#687 Add libimage/manifests.LockerForImage()
  libimage/manifests/manifests.go
  libimage/manifests/manifests_test.go
Labels: approved

#696 vendor in containers/storage v1.33.0
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/drivers/quota/projectquota.go
  vendor/github.com/containers/storage/drivers/quota/projectquota_unsupported.go
  vendor/github.com/containers/storage/go.mod
  vendor/github.com/containers/storage/go.sum
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/archive/archive_unix.go
  vendor/github.com/containers/storage/pkg/chunked/compression.go
  vendor/github.com/containers/storage/pkg/chunked/compressor/compressor.go
  vendor/github.com/containers/storage/pkg/chunked/internal/compression.go
  vendor/github.com/containers/storage/pkg/chunked/storage_linux.go
  vendor/github.com/containers/storage/storage.conf
  vendor/github.com/containers/storage/types/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#698 Use authfile in options to search image
  libimage/search.go
Labels: approved, lgtm

#697 pull policy: support camel cases
  pkg/config/pull_policy.go
Labels: approved, lgtm

#700 Remove `--accept-repositories` flag
  pkg/auth/cli.go
Labels: approved, lgtm

#699 bump to v0.42
  version/version.go
Labels: approved, lgtm
