Repository containers/common, pull requests merged in 2021-06, with the labels that each got.

#514 add passdriver for secrets.
  .cirrus.yml
  pkg/secrets/passdriver/passdriver.go
  pkg/secrets/passdriver/passdriver_test.go
  pkg/secrets/secrets.go
Labels: approved, lgtm

#597 seccomp: allow more *_time64 syscalls
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved, lgtm

#598 secrets: fix build with go 1.15
  pkg/secrets/passdriver/passdriver.go
Labels: approved, lgtm

#604 Leave default seccomp path empty
  pkg/config/default.go
Labels: approved, lgtm

#606 made necessary changes to handle OS/Arch while importing an image
  libimage/import.go
Labels: approved, lgtm

#608 0.38 backports
  pkg/config/default.go
  version/version.go
Labels: approved, lgtm

#609 libimage: pull: turn image-lookup errors non-fatal
  libimage/pull.go
Labels: approved, lgtm

#610 0.38 backports
  libimage/pull.go
  version/version.go
Labels: approved, lgtm

#613 add @Luap99 to OWNERS
  OWNERS
Labels: approved, lgtm

#612 libmage: Exists: catch corrupted images
  libimage/corrupted_test.go
  libimage/runtime.go
Labels: approved, lgtm

#605 Add default for log-tag
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/testdata/containers_override.conf
Labels: approved, lgtm

#603 fix autodiscovery of the secret passdriver.
  pkg/secrets/passdriver/passdriver.go
Labels: approved, lgtm

#614 0.38 backports
  libimage/corrupted_test.go
  libimage/runtime.go
  version/version.go
Labels: approved, lgtm

#602 add 'secret' section to the containers.conf struct.
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_local_test.go
  pkg/config/containers.conf
  pkg/config/default.go
  pkg/config/testdata/containers_override.conf
Labels: approved, lgtm

#618 0.38 backports
  libimage/corrupted_test.go
  libimage/runtime.go
  version/version.go
Labels: approved, lgtm

#617 libimage: fix Exists
  libimage/corrupted_test.go
  libimage/runtime.go
Labels: approved, lgtm

#616 [NO TESTS NEEDED] Sort containers.conf and containers.conf.5.md
  docs/containers.conf.5.md
  pkg/config/containers.conf
Labels: approved, lgtm

#615 Add support for config drop in directories
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm

#620 Fix spacing on name value pairs to be consistent
  pkg/config/containers.conf
Labels: approved, lgtm

#623 seccomp: allow timer_settime64
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved, lgtm

#573 seccomp: switch default to ENOSYS
  pkg/seccomp/conversion.go
  pkg/seccomp/default_linux.go
  pkg/seccomp/filter.go
  pkg/seccomp/seccomp.json
  pkg/seccomp/seccomp_linux.go
  pkg/seccomp/types.go
Labels: approved, lgtm

#624 Strip extra trailing newlines in templates
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#607 Use SetCredentials and add verbose to loginopts
  pkg/auth/auth.go
  pkg/auth/cli.go
Labels: approved, lgtm

#626 Bump to v0.40.0
  version/version.go
Labels: approved

#628 Set BigFilesTemporaryDir to GetEnv(TMPDIR) if set or /var/tmp
  libimage/download.go
  libimage/runtime.go
  libimage/runtime_test.go
Labels: approved, lgtm

#630 libimage: force remove: only untag on multi tag image
  go.mod
  go.sum
  libimage/image.go
  libimage/load_test.go
  libimage/remove_test.go
  vendor/github.com/containers/image/v5/storage/storage_image.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#622 libimage: lookup images by custom platform
  libimage/pull.go
  libimage/pull_test.go
  libimage/runtime.go
Labels: approved, lgtm

#633 [0.38] libimage: force remove: only untag on multi tag image
  libimage/image.go
  libimage/load_test.go
  libimage/remove_test.go
Labels: approved, lgtm

#627 seccomp: tweak default profile (followup for #573)
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved, lgtm

#635 Vendor in containers/image v5.13.2
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#636 Bump to v0.40.1
  version/version.go
Labels: approved

#639 Allow /etc/containers/containers.conf to be read by non-root
  pkg/config/config.go
  pkg/config/config_local_test.go
Labels: approved, lgtm

#634 libimage: pull: ignore platform for local image lookup
  libimage/corrupted_test.go
  libimage/image.go
  libimage/pull.go
  libimage/runtime.go
Labels: approved, lgtm, needs-backport

#642 revert runc bump
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/aufs/aufs.go
  vendor/github.com/containers/storage/drivers/copy/copy_linux.go
  vendor/github.com/containers/storage/drivers/fsdiff.go
  vendor/github.com/containers/storage/drivers/overlay/check.go
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/go.mod
  vendor/github.com/containers/storage/go.sum
  vendor/github.com/containers/storage/pkg/archive/archive.go
  vendor/github.com/containers/storage/pkg/archive/archive_freebsd.go
  vendor/github.com/containers/storage/pkg/archive/archive_unix.go
  vendor/github.com/containers/storage/pkg/chrootarchive/archive.go
  vendor/github.com/containers/storage/pkg/chrootarchive/diff_unix.go
  vendor/github.com/coreos/go-systemd/v22/dbus/dbus.go
  vendor/github.com/coreos/go-systemd/v22/dbus/methods.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/fscommon.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/open.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/network.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_32.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
  vendor/github.com/opencontainers/runc/libcontainer/system/userns_deprecated.go
  vendor/github.com/opencontainers/runc/libcontainer/system/xattrs_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, lgtm

#644 0.38 backports plus bump to v0.38.10
  libimage/corrupted_test.go
  libimage/image.go
  libimage/pull.go
  libimage/runtime.go
  pkg/config/config.go
  pkg/config/config_local_test.go
  version/version.go
Labels: approved, lgtm

#646 libimage: `(*Runtime).SystemContext()`
  libimage/runtime.go
  libimage/runtime_test.go
Labels: approved, lgtm

#647 Podman v3.2.2 backports
  libimage/download.go
  libimage/runtime.go
  libimage/runtime_test.go
  pkg/report/template.go
  pkg/report/template_test.go
Labels: approved, lgtm

#650 bump to v0.38.11
  version/version.go
Labels: approved, lgtm

#652 0.38 backports
  libimage/pull.go
  version/version.go
Labels: approved, lgtm

#651 pull: custom platform: do not use local image name
  libimage/pull.go
Labels: approved, lgtm

#648 Created nummem_linux.go and nummem_unsupported.go
  pkg/sysinfo/numcpu_linux.go
  pkg/sysinfo/nummem_linux.go
  pkg/sysinfo/nummem_unsupported.go
  pkg/sysinfo/sysinfo_linux_test.go
Labels: approved, lgtm

#655 libimage: events: deferred write
  libimage/image.go
  libimage/load.go
  libimage/manifest_list.go
  libimage/pull.go
  libimage/push.go
  libimage/save.go
Labels: approved, lgtm

#637 feat: add shell secret driver.
  pkg/secrets/secrets.go
  pkg/secrets/shelldriver/shelldriver.go
  pkg/secrets/shelldriver/shelldriver_test.go
Labels: approved, lgtm
