Repository containers/common, pull requests merged in 2021-01, with the labels that each got.

#393 http_proxy is supposed to default to true.
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/default.go
Labels: approved, lgtm

#392 Do not retry on most syscall failures
  pkg/retry/retry.go
Labels: approved, lgtm

#394 Bump to v0.32.0
  version/version.go
Labels: approved

#396 Current code fails to compile on Darwin no syscall.ERESTART
  Makefile
  pkg/retry/retry.go
  pkg/retry/retry_linux.go
  pkg/retry/retry_unsupported.go
Labels: approved, lgtm

#397 Bump to v0.32.1
  version/version.go
Labels: approved

#375 Implement secrets pkg: backend and filedriver
  pkg/secrets/filedriver/filedriver.go
  pkg/secrets/filedriver/filedriver_test.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
  pkg/secrets/secretsdb.go
Labels: approved, lgtm

#398 Add new function to setup default environment
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm

#399 seccomp: drop 'vmsplice' from the allowed list
  pkg/seccomp/default_linux.go
  pkg/seccomp/seccomp.json
Labels: approved, lgtm

#400 Update vendor of containers/storage
  go.mod
  go.sum
  vendor/github.com/containers/storage/VERSION
  vendor/github.com/containers/storage/drivers/overlay/overlay.go
  vendor/github.com/containers/storage/go.mod
  vendor/github.com/containers/storage/go.sum
  vendor/github.com/containers/storage/pkg/idtools/idtools.go
  vendor/github.com/containers/storage/store.go
  vendor/github.com/containers/storage/utils.go
  vendor/github.com/klauspost/compress/zstd/decoder.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/zstd.go
  vendor/modules.txt
Labels: approved, lgtm

#401 Bump to v0.33.0
  version/version.go
Labels: approved

#402 Move to v0.34.0-dev
  version/version.go
Labels: approved

#403 Rename internal functions to make them easier to understand
  pkg/retry/retry.go
  pkg/retry/retry_linux.go
  pkg/retry/retry_unsupported.go
Labels: approved, lgtm

#405 Fix secret name regex
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
Labels: approved, lgtm

#408 config: fix runtime_supports_nocgroup key name
  pkg/config/config.go
Labels: approved, lgtm

#407 fix - make target all on osx
  Makefile
Labels: approved, lgtm

#409 Back port a few fixes, Bump to v0.33.1
  Makefile
  pkg/config/config.go
  pkg/retry/retry.go
  pkg/retry/retry_linux.go
  pkg/retry/retry_unsupported.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
  version/version.go
Labels: approved, lgtm

#413 Fix name validation and dir mode in secrets
  pkg/secrets/filedriver/filedriver.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
Labels: approved, do-not-merge/hold, lgtm

#414 Fix secret name validation
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
Labels: approved, lgtm

#417 Add accessor for log-driver
  pkg/config/default.go
Labels: approved, lgtm

#418 cgroupv2: fix typo in comment
  pkg/cgroupv2/cgroups_linux.go
  pkg/cgroupv2/cgroups_unsupported.go
Labels: approved, lgtm

#416 Fix secret create prefix
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
  pkg/secrets/secretsdb.go
Labels: approved, lgtm

#415 Add image_parallel_copies engine config
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/testdata/containers_override.conf
Labels: approved, lgtm

#422 pkg: check ownership for XDG_RUNTIME_DIR
  pkg/config/util_supported.go
Labels: approved, lgtm

#421 seccomp: various updates
  Makefile
  pkg/seccomp/default_linux.go
  pkg/seccomp/generate.go
  pkg/seccomp/seccomp.json
  tools/validate_seccomp.sh
Labels: approved, lgtm

#420 Add U volume flag to chown source volumes
  pkg/chown/chown.go
  pkg/chown/chown_test.go
  pkg/parse/parse.go
Labels: approved, lgtm
