Repository containers/common, pull requests merged in 2023-09, with the labels that each got.

#1312 Add restore handler for password input
  pkg/auth/auth.go
  pkg/util/util.go
  pkg/util/util_supported.go
  pkg/util/util_windows.go
Labels: lgtm, approved

#1632 enable more linters
  .golangci.yml
  libimage/filters.go
  libimage/image_config.go
  libimage/import.go
  libimage/pull.go
  libnetwork/cni/config_test.go
  libnetwork/netavark/config_test.go
  libnetwork/netavark/exec.go
  libnetwork/netavark/ipam.go
  libnetwork/netavark/network.go
  libnetwork/network/interface.go
  libnetwork/types/network_test.go
  pkg/apparmor/apparmor_linux_template.go
  pkg/auth/auth.go
  pkg/cgroups/blkio_linux.go
  pkg/cgroups/cgroups_linux.go
  pkg/cgroups/systemd_linux.go
  pkg/cgroups/utils_linux.go
  pkg/config/config.go
  pkg/config/config_local_test.go
  pkg/config/default_linux.go
  pkg/configmaps/configmaps.go
  pkg/configmaps/filedriver/filedriver.go
  pkg/flag/flag.go
  pkg/formats/formats.go
  pkg/hooks/monitor_test.go
  pkg/report/camelcase/camelcase.go
  pkg/retry/retry.go
  pkg/secrets/filedriver/filedriver.go
  pkg/secrets/shelldriver/shelldriver.go
  pkg/ssh/connection_golang.go
  pkg/ssh/connection_native.go
  pkg/ssh/utils.go
  pkg/subscriptions/subscriptions.go
  pkg/umask/umask_test.go
Labels: lgtm, approved

#1646 libimage: split out search filters
  libimage/filter/filter.go
  libimage/search.go
Labels: lgtm, approved

#1652 Bump to v0.56.0
  version/version.go
Labels: approved

#1653 Fix typo in comment
  pkg/config/default.go
Labels: lgtm, approved

#1656 Fix specification of unix:///run
  docs/containers.conf.5.md
  pkg/config/containers.conf
  pkg/config/containers.conf-freebsd
Labels: lgtm, approved, 4.7

#1651 libimage/layer_tree: if parent is empty and a manifest list then ignore check.
  libimage/layer_tree.go
Labels: lgtm, approved

#1657 Split up util package into pkg/password, pkg/copy, pkg/version
  libnetwork/cni/network.go
  libnetwork/netavark/network.go
  libnetwork/util/filters.go
  pkg/auth/auth.go
  pkg/detach/copy.go
  pkg/filters/filters.go
  pkg/password/password_supported.go
  pkg/password/password_windows.go
  pkg/util/util.go
  pkg/util/util_supported.go
  pkg/util/util_windows.go
  pkg/version/version.go
Labels: lgtm, approved

#1640 Remove ActiveDestination method to move into podman
  pkg/config/config.go
  pkg/config/config_test.go
Labels: lgtm, approved, 4.7

#1659 Default machine CPUs to Cores/2
  pkg/config/config_local_test.go
  pkg/config/default.go
  pkg/config/testdata/containers_default.conf
Labels: lgtm, approved

#1660 pkg/config: do NOT set StaticDir and VolumeDir
  pkg/config/config.go
  pkg/config/default.go
Labels: lgtm, approved

#1661 Implement negated label match function
  pkg/filters/filters.go
  pkg/filters/filters_test.go
Labels: lgtm, approved

#1665 chore: import packages only once
  libimage/manifests/manifests.go
Labels: lgtm, approved

#1668 libnetwork/cni: ignore ENOENT while reading networks
  libnetwork/cni/network.go
Labels: lgtm, approved

#1671 Makefile, libimage: `test-unit` must cover `libimage/manifests_test.go`
  Makefile
  libimage/manifests/manifests_test.go
Labels: lgtm, approved

#1673 Add support for vrf option on netavark
  libnetwork/netavark/config.go
  libnetwork/netavark/config_test.go
  libnetwork/netavark/testfiles/valid/vrf.json
  libnetwork/types/const.go
Labels: lgtm, approved

#1666 libimage: implement `retry` logic for `manifest push`
  libimage/manifest_list.go
  libimage/manifests/manifests.go
  libimage/manifests/manifests_test.go
Labels: lgtm, approved

#1670 Add list members emails to the CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved

#1677 Use MatchNegatedLabelFilter function for networks
  libnetwork/util/filters.go
Labels: lgtm, approved

#1667 pkg/subscriptions: add /etc/crypto-policies/config in fips mode
  pkg/subscriptions/subscriptions.go
Labels: lgtm, approved

#1676 Fix ID and Digest filters
  libimage/filters.go
  libimage/filters_test.go
  libimage/image.go
Labels: lgtm, approved
