Repository containers/common, pull requests merged in 2023-10, with the labels that each got.

#1682 URGENT: heal CI: fix codespell
  docs/Containerfile.5.md
  libimage/copier.go
  libimage/filters.go
  libnetwork/netavark/network.go
  pkg/config/config.go
Labels: lgtm, approved

#1684 Makefile: simplify unit tests
  Makefile
Labels: lgtm, approved

#1675 POC: appendable string arrays in containers.conf
  internal/attributed-string-slice/attributed_string_slice.go
  internal/attributed-string-slice/attributed_string_slice_test.go
Labels: lgtm, approved

#1683 containers.conf: add `privileged` field to containers table
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/containers.conf-freebsd
  pkg/config/testdata/containers_override.conf
Labels: lgtm, approved

#1689 apparmor: fix parsing beta/alpha version
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved

#1692 pkg/config: use empty default for db_backend
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/containers.conf-freebsd
  pkg/config/db_backend.go
  pkg/config/db_backend_test.go
  pkg/config/default.go
Labels: lgtm, approved

#1693 Move platform code to its own directory
  libimage/copier.go
  libimage/define/platform.go
  libimage/image.go
  libimage/normalize_test.go
  libimage/platform.go
  libimage/platform/platform.go
  libimage/platform/platform_test.go
  libimage/runtime.go
Labels: lgtm, approved

#1696 libimage: add compat interfaces for the new platform subpackage
  libimage/platform.go
Labels: lgtm, approved, do-not-merge/hold

#1697 libimage: fix computing history
  libimage/history.go
  libimage/history_test.go
Labels: lgtm, approved

#1700 libimage: support parallel tag/untag
  libimage/image.go
  libimage/image_test.go
Labels: lgtm, approved

#1701 libimage: Untag should error for non existent name
  libimage/image.go
  libimage/image_test.go
Labels: lgtm, approved

#1704 Copier: use StringWithinTransport instead of DockerReference
  libimage/copier.go
Labels: lgtm, approved

#1707 containers.conf: appendable string arrays, Part 1
  internal/attributed-string-slice/attributed_string_slice.go
  internal/attributedstring/slice.go
  internal/attributedstring/slice_test.go
  pkg/config/config.go
  pkg/config/config_local_test.go
  pkg/config/config_test.go
  pkg/config/default.go
  pkg/config/modules_test.go
  pkg/config/testdata/modules/etc/containers/containers.conf.modules/fourth.conf
  pkg/config/testdata/modules/home/.config/containers/containers.conf.modules/second.conf
  pkg/config/testdata/modules/usr/share/containers/containers.conf.modules/sub/share-only.conf
Labels: lgtm, approved

#1710 containers.conf: turn all `[]string` into `attributedstring.Slice`
  internal/attributedstring/slice.go
  libnetwork/network/interface.go
  libnetwork/pasta/pasta.go
  libnetwork/slirp4netns/slirp4netns.go
  pkg/config/config.go
  pkg/config/config_local.go
  pkg/config/config_local_test.go
  pkg/config/config_remote_test.go
  pkg/config/config_test.go
  pkg/config/default.go
  pkg/config/modules_test.go
Labels: lgtm, approved

#1716 cgroups: remove unused files
  pkg/cgroups/blkio.go
  pkg/cgroups/cgroups.go
  pkg/cgroups/cgroups_linux.go
  pkg/cgroups/cgroups_test.go
  pkg/cgroups/cpu.go
  pkg/cgroups/cpuset.go
  pkg/cgroups/memory.go
  pkg/cgroups/pids.go
  pkg/cgroups/utils.go
Labels: lgtm, approved

#1717 Add masked paths and readonly paths to config
  pkg/config/default.go
Labels: lgtm, approved

#1718 Add back SystemCPUUsage
  pkg/cgroups/cgroups_linux.go
Labels: lgtm, approved

#1719 containers.conf: append to string arrays
  docs/containers.conf.5.md
Labels: lgtm, approved

#1720 UserConnection is used by non linux platforms
  pkg/cgroups/cgroups_linux.go
  pkg/cgroups/cgroups_supported.go
  pkg/cgroups/utils_linux.go
Labels: lgtm, approved, breaking-change
