Repository containers/common, pull requests merged in 2024-01, with the labels that each got.

#1779 Move minimal golang to v1.20
  go.mod
Labels: lgtm, approved

#1781 Fix typos across repo; extend codespell config
  .codespelldict
  .codespellrc
  .github/workflows/validate.yml
  Makefile
  docs/containers.conf.5.md
  internal/attributedstring/slice_test.go
  libimage/copier.go
  libimage/image.go
  libimage/image_test.go
  libimage/image_tree.go
  libimage/manifest_list.go
  libimage/pull.go
  libimage/push.go
  libimage/runtime.go
  libnetwork/cni/run_test.go
  libnetwork/internal/util/interface.go
  libnetwork/netavark/config_test.go
  libnetwork/netavark/run_test.go
  libnetwork/netavark/testfiles/invalid/name_mismatch.json
  pkg/capabilities/capabilities_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/configmaps/filedriver/filedriver.go
  pkg/seccomp/seccomp_unsupported.go
  pkg/secrets/filedriver/filedriver.go
  pkg/ssh/connection_golang.go
Labels: lgtm, approved

#1784 Refactor: replace raw loops with funcs from slices and maps
  go.mod
  libnetwork/cni/cni_conversion.go
  libnetwork/cni/config.go
  libnetwork/etchosts/hosts.go
  libnetwork/internal/util/bridge.go
  libnetwork/internal/util/util.go
  libnetwork/netavark/config.go
  libnetwork/netavark/run.go
  libnetwork/resolvconf/resolv.go
  libnetwork/util/filters.go
  pkg/capabilities/capabilities.go
  pkg/capabilities/capabilities_test.go
  pkg/cgroups/cgroups_linux.go
  pkg/config/config.go
  pkg/configmaps/configmaps.go
  pkg/configmaps/filedriver/filedriver.go
  pkg/secrets/filedriver/filedriver.go
  pkg/secrets/secrets.go
  pkg/ssh/connection_golang.go
  pkg/util/util.go
Labels: lgtm, approved

#1786 Fix staticcheck issues; show all lint issues in CI
  .github/workflows/validate.yml
  libimage/runtime.go
Labels: lgtm, approved

#1787 Simplify tests with testing.TempDir instead of os.MkdirTemp
  libimage/corrupted_test.go
  libimage/filters_test.go
  libimage/history_test.go
  libimage/image_test.go
  libimage/import_test.go
  libimage/load_test.go
  libimage/manifest_list_test.go
  libimage/manifests/manifests_test.go
  libimage/pull_test.go
  libimage/push_test.go
  libimage/remove_test.go
  libimage/runtime_test.go
  libimage/save_test.go
  pkg/chown/chown_test.go
  pkg/configmaps/configmaps_test.go
  pkg/configmaps/filedriver/filedriver_test.go
  pkg/hooks/exec/exec_test.go
  pkg/secrets/filedriver/filedriver_test.go
  pkg/secrets/passdriver/passdriver_test.go
  pkg/secrets/secrets_test.go
  pkg/secrets/shelldriver/shelldriver_test.go
  pkg/supplemented/supplemented_test.go
  pkg/sysinfo/sysinfo_linux_test.go
Labels: lgtm, approved

#1789 Refactor map init with short declaration syntax
  internal/attributedstring/slice.go
  libimage/manifest_list_test.go
  libnetwork/cni/cni_types.go
  libnetwork/cni/run.go
  pkg/cgroups/cgroups_linux.go
  pkg/config/default.go
  pkg/secrets/secrets_test.go
Labels: lgtm, approved

#1788 chore: replace 'interface{}' with 'any' for consistency
  .golangci.yml
  internal/attributedstring/slice.go
  libnetwork/cni/cni_conversion.go
  libnetwork/cni/cni_types.go
  libnetwork/cni/run.go
  libnetwork/netavark/exec.go
  libnetwork/netavark/ipam.go
  libnetwork/netavark/netavark_suite_test.go
  libnetwork/slirp4netns/slirp4netns.go
  pkg/apparmor/internal/supported/supportedfakes/fake_verifier_impl.go
  pkg/formats/formats.go
  pkg/formats/templates.go
  pkg/report/formatter.go
  pkg/report/template.go
  pkg/ssh/types.go
  pkg/systemd/systemd_linux.go
Labels: lgtm, approved

#1794 [release-0.52] [crio-1.26] Cherry-pick changes from containers/common/pull#1689
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/bug

#1795 [release-0.52] [crio-1.25] Cherry-pick changes from containers/common/pull#1689
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/bug

#1797 [release-0.55] [crio-1.28] Cherry-pick changes from containers/common/pull#1689
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/bug

#1793 [release-0.46] [crio-1.24] Cherry-pick changes from containers/common/pull#1689
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/bug

#1796 [release-0.53] [crio-1.27] Cherry-pick changes from containers/common/pull#1689
  pkg/apparmor/apparmor_linux.go
Labels: lgtm, approved, kind/bug

#1801 Drop warning to info on missing content from mounts.conf
  pkg/subscriptions/subscriptions.go
Labels: lgtm, approved

#1807 Bump c/image to v5.29.1, common to 0.57.2, then to common 0.57.3-dev
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/docker_image.go
  vendor/github.com/containers/image/v5/docker/docker_image_dest.go
  vendor/github.com/containers/image/v5/docker/docker_image_src.go
  vendor/github.com/containers/image/v5/docker/docker_transport.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
  version/version.go
Labels: lgtm, approved

#1809 containers.conf: add crun-vm as a runtime
  docs/containers.conf.5.md
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/default.go
Labels: lgtm, approved

#1800 Fix image filters parsing
  libimage/filters.go
  libimage/filters_test.go
  pkg/filters/filters.go
  pkg/filters/filters_test.go
Labels: lgtm, approved

#1815 libimage/manifests/manifests_test.go: use assert.NoError
  libimage/manifests/manifests_test.go
Labels: lgtm, approved

#1817 pkg/manifests.list: add SetMediaType(), SetArtifactType()
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved

#1816 pkg/manifests.list.preferOCI() learn about some new OCI fields
  pkg/manifests/manifests.go
Labels: lgtm, approved

#1818 add ConfigureTimeZone for all Unix based platforms
  pkg/timezone/timezone.go
  pkg/timezone/timezone_unsupported.go
Labels: lgtm, approved

#1814 New global option interface_name in containers.conf
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_local.go
  pkg/config/config_local_test.go
  pkg/config/config_remote.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/testdata/containers_comment.conf
  pkg/config/testdata/containers_default.conf
Labels: lgtm, approved

#1824 Fix `podman system df` panic
  libimage/layer_tree.go
Labels: lgtm, approved

#1820 Change default image volume mode to "anonymous"
  pkg/config/config.go
  pkg/config/config_darwin.go
  pkg/config/config_freebsd.go
  pkg/config/config_linux.go
  pkg/config/config_test.go
  pkg/config/containers.conf
  pkg/config/default.go
Labels: lgtm, approved

#1826 pkg/config: rework system connections and farm storage
  docs/containers.conf.5.md
  pkg/config/config.go
  pkg/config/config_darwin.go
  pkg/config/config_freebsd.go
  pkg/config/config_linux.go
  pkg/config/config_local_test.go
  pkg/config/config_test.go
  pkg/config/config_unix.go
  pkg/config/config_windows.go
  pkg/config/connections.go
  pkg/config/connections_test.go
  pkg/config/containers.conf
  pkg/config/new.go
  pkg/ssh/connection_golang.go
  pkg/ssh/connection_native.go
Labels: lgtm, approved

#1819 pkg/manifests.list.AddInstance(): don't set Platform to an empty struct
  pkg/filters/filters_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved

#1835 [v0.57] Bump c/image to v5.29.2, common to v0.57.3, then v0.57.4-dev
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/daemon/client.go
  vendor/github.com/containers/image/v5/version/version.go
  vendor/modules.txt
  version/version.go
Labels: lgtm, approved

#1767 Gate CNI support behind the `cni` build tag
  .golangci.yml
  Makefile
  libnetwork/cni/cni_conversion.go
  libnetwork/cni/cni_exec.go
  libnetwork/cni/cni_suite_test.go
  libnetwork/cni/cni_types.go
  libnetwork/cni/config.go
  libnetwork/cni/config_freebsd.go
  libnetwork/cni/config_linux.go
  libnetwork/cni/config_test.go
  libnetwork/cni/network.go
  libnetwork/cni/run.go
  libnetwork/cni/run_test.go
  libnetwork/network/interface.go
  libnetwork/network/interface_cni.go
  libnetwork/network/interface_cni_unsupported.go
Labels: lgtm, approved

#1821 Make timezone work on freebsd
  pkg/timezone/timezone.go
  pkg/timezone/timezone_linux.go
  pkg/timezone/timezone_unix.go
  pkg/timezone/timezone_windows.go
Labels: lgtm, approved, 5.0
